#!/bin/bash

echo
echo "------------------------"
echo "---Compilation start!---"
echo "------------------------"
echo



if [ ! -d build ]
then
	echo "'build' folder doesn't exist"
	echo "Creating 'build' folder"
	mkdir build	
fi

cd build

compilation(){
	cmake ..
	cmake --build .
	
	echo	
	echo "---Compilation time---"
}



time compilation
echo "----------------------"


echo
echo "---------------------------"
echo "---Compilation complete!---"
echo "---------------------------"
echo
